//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MtomClientConsole.LocalServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MtomTestSite")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyMtomData", Namespace="http://schemas.datacontract.org/2004/07/MtomTestSite")]
    [System.SerializableAttribute()]
    public partial class MyMtomData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] File1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] File2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] File1 {
            get {
                return this.File1Field;
            }
            set {
                if ((object.ReferenceEquals(this.File1Field, value) != true)) {
                    this.File1Field = value;
                    this.RaisePropertyChanged("File1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] File2 {
            get {
                return this.File2Field;
            }
            set {
                if ((object.ReferenceEquals(this.File2Field, value) != true)) {
                    this.File2Field = value;
                    this.RaisePropertyChanged("File2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataLen", ReplyAction="http://tempuri.org/IService1/GetDataLenResponse")]
        string GetDataLen(string name, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataLen", ReplyAction="http://tempuri.org/IService1/GetDataLenResponse")]
        System.Threading.Tasks.Task<string> GetDataLenAsync(string name, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataLenStream", ReplyAction="http://tempuri.org/IService1/GetDataLenStreamResponse")]
        string GetDataLenStream(System.IO.Stream data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataLenStream", ReplyAction="http://tempuri.org/IService1/GetDataLenStreamResponse")]
        System.Threading.Tasks.Task<string> GetDataLenStreamAsync(System.IO.Stream data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        MtomClientConsole.LocalServiceReference1.CompositeType GetDataUsingDataContract(MtomClientConsole.LocalServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MtomClientConsole.LocalServiceReference1.CompositeType> GetDataUsingDataContractAsync(MtomClientConsole.LocalServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMyMtomData", ReplyAction="http://tempuri.org/IService1/GetMyMtomDataResponse")]
        MtomClientConsole.LocalServiceReference1.MyMtomData GetMyMtomData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMyMtomData", ReplyAction="http://tempuri.org/IService1/GetMyMtomDataResponse")]
        System.Threading.Tasks.Task<MtomClientConsole.LocalServiceReference1.MyMtomData> GetMyMtomDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RoundTripMyMtomData", ReplyAction="http://tempuri.org/IService1/RoundTripMyMtomDataResponse")]
        MtomClientConsole.LocalServiceReference1.MyMtomData RoundTripMyMtomData(MtomClientConsole.LocalServiceReference1.MyMtomData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RoundTripMyMtomData", ReplyAction="http://tempuri.org/IService1/RoundTripMyMtomDataResponse")]
        System.Threading.Tasks.Task<MtomClientConsole.LocalServiceReference1.MyMtomData> RoundTripMyMtomDataAsync(MtomClientConsole.LocalServiceReference1.MyMtomData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MtomClientConsole.LocalServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MtomClientConsole.LocalServiceReference1.IService1>, MtomClientConsole.LocalServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetDataLen(string name, byte[] data) {
            return base.Channel.GetDataLen(name, data);
        }
        
        public System.Threading.Tasks.Task<string> GetDataLenAsync(string name, byte[] data) {
            return base.Channel.GetDataLenAsync(name, data);
        }
        
        public string GetDataLenStream(System.IO.Stream data) {
            return base.Channel.GetDataLenStream(data);
        }
        
        public System.Threading.Tasks.Task<string> GetDataLenStreamAsync(System.IO.Stream data) {
            return base.Channel.GetDataLenStreamAsync(data);
        }
        
        public MtomClientConsole.LocalServiceReference1.CompositeType GetDataUsingDataContract(MtomClientConsole.LocalServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MtomClientConsole.LocalServiceReference1.CompositeType> GetDataUsingDataContractAsync(MtomClientConsole.LocalServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public MtomClientConsole.LocalServiceReference1.MyMtomData GetMyMtomData() {
            return base.Channel.GetMyMtomData();
        }
        
        public System.Threading.Tasks.Task<MtomClientConsole.LocalServiceReference1.MyMtomData> GetMyMtomDataAsync() {
            return base.Channel.GetMyMtomDataAsync();
        }
        
        public MtomClientConsole.LocalServiceReference1.MyMtomData RoundTripMyMtomData(MtomClientConsole.LocalServiceReference1.MyMtomData data) {
            return base.Channel.RoundTripMyMtomData(data);
        }
        
        public System.Threading.Tasks.Task<MtomClientConsole.LocalServiceReference1.MyMtomData> RoundTripMyMtomDataAsync(MtomClientConsole.LocalServiceReference1.MyMtomData data) {
            return base.Channel.RoundTripMyMtomDataAsync(data);
        }
    }
}
